# Generated by Django 6.0 on 2025-12-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('class_applied', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age_completed', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=200)),
                ('father_occupation', models.CharField(max_length=200)),
                ('father_contact', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_occupation', models.CharField(max_length=200)),
                ('mother_contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('has_previous_schooling', models.BooleanField(default=False)),
                ('previous_school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission Inquiry',
                'verbose_name_plural': 'Admission Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionsFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admissions FAQ',
                'verbose_name_plural': 'Admissions FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Admissions Overview', max_length=200)),
                ('hero_description', models.TextField(default="Join the Nethaji Vidyalayam family. A simple, transparent process to begin your child's journey of excellence.")),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='admissions/')),
                ('why_sub_heading', models.CharField(default='Why Choose Us?', max_length=200)),
                ('why_heading', models.CharField(default='Nurturing Potential, Shaping Futures', max_length=200)),
                ('why_description', models.TextField(default='At our school, we are committed to providing a nurturing and stimulating learning environment that supports the holistic development of every child.')),
                ('why_image', models.ImageField(blank=True, null=True, upload_to='admissions/')),
                ('cta_title', models.CharField(default='Ready to Join Us?', max_length=200)),
                ('cta_description', models.TextField(default="Take the first step towards your child's bright future. Schedule a campus visit or contact our admissions office today.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admissions Page Content',
                'verbose_name_plural': 'Admissions Page Content',
            },
        ),
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g. ClipboardCheck, FileText, Users, CheckCircle)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AgeCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('min_age', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Age Criterion',
                'verbose_name_plural': 'Age Criteria',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
