# Generated by Django 6.0 on 2025-12-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FacilitiesPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Facilities', max_length=200)),
                ('hero_description', models.CharField(default='World-class infrastructure for holistic development', max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('intro_badge', models.CharField(default='Infrastructure', max_length=100)),
                ('intro_title', models.CharField(default='Where Learning Meets Excellence', max_length=200)),
                ('intro_description_1', models.TextField(default="At Nethaji Vidyalayam, we believe that a conducive learning environment is essential for academic and personal growth. Our campus is equipped with state-of-the-art facilities designed to support every aspect of a child's development—from academics to sports, arts, and overall well-being.")),
                ('intro_description_2', models.TextField(default='Safety, hygiene, and accessibility are our top priorities, ensuring that every student has the resources they need to excel.')),
                ('tech_badge', models.CharField(default='Digital Learning', max_length=100)),
                ('tech_title', models.CharField(default='Technology-Integrated Education', max_length=200)),
                ('tech_description', models.TextField(default='We leverage technology to enhance learning outcomes. Every classroom is equipped with interactive smart boards, projectors, and high-speed internet. Students have access to online learning portals, digital assignments, and e-library resources.')),
                ('tech_image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('green_title', models.CharField(default='Eco-Friendly Campus', max_length=200)),
                ('green_description', models.TextField(default='Committed to sustainability and environmental responsibility.')),
                ('cta_title', models.CharField(default='Experience Our Campus', max_length=200)),
                ('cta_description', models.TextField(default='Schedule a campus visit or take a virtual tour to see our facilities in action.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facilities Page Content',
                'verbose_name_plural': 'Facilities Page Content',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='facilities/main/')),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g. FlaskConical, Laptop, BookOpen)', max_length=50)),
                ('features', models.JSONField(default=list, help_text="List of features as a JSON array (e.g. ['Feature 1', 'Feature 2'])")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FacilityStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FacilityTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GreenInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SafetyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Shield', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('icon_name', models.CharField(default='Wifi', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
