# Generated by Django 5.1.5 on 2025-12-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Nethaji Vidyalayam', max_length=200)),
                ('video_url', models.URLField(help_text='Link to the background video (e.g. YouTube/Vimeo direct link or static asset)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Video',
                'verbose_name_plural': 'Hero Videos',
            },
        ),
    ]
