# Generated by Django 5.1.5 on 2025-12-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload local video file (optional if URL provided)', null=True, upload_to='hero_videos/'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Direct link to external video (optional if file uploaded)', max_length=500, null=True),
        ),
    ]
