# Generated by Django 5.1.5 on 2025-12-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herovideo_video_file_alter_herovideo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(default='Welcome to Nethaji', max_length=200)),
                ('heading', models.CharField(default='Nurturing the Future Leaders', max_length=200)),
                ('description', models.TextField(help_text='Use <br> for line breaks if needed, or stick to simple paragraphs.')),
                ('button_text', models.CharField(default='Discover Our Story', max_length=100)),
                ('button_link', models.CharField(default='/about', max_length=200)),
                ('image1', models.ImageField(help_text='Main vertical image', upload_to='home_about/')),
                ('image2', models.ImageField(help_text='Top right image', upload_to='home_about/')),
                ('image3', models.ImageField(help_text='Bottom right image', upload_to='home_about/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home About Section',
                'verbose_name_plural': 'Home About Section',
            },
        ),
    ]
