# Generated by Django 5.1.5 on 2025-12-20 10:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homeabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Provide the about section description.'),
        ),
    ]
