# Generated by Django 5.1.5 on 2025-12-20 10:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homeabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Provide the about section description.'),
        ),
    ]
