# Generated by Django 6.0 on 2025-12-20 12:57

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='A Legacy of Excellence', max_length=200)),
                ('hero_sub_title', models.CharField(default='Who We Are', max_length=200)),
                ('hero_description', models.TextField(default='Since 2001, Nethaji Vidyalayam has been a beacon of knowledge, shaping young minds into global leaders.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about_page/')),
                ('story_sub_heading', models.CharField(default='Our Story', max_length=200)),
                ('story_heading', models.CharField(default='From Humble Beginnings to Educational Excellence', max_length=200)),
                ('story_description', django_ckeditor_5.fields.CKEditor5Field()),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='about_page/')),
                ('stat1_value', models.CharField(default='20+', max_length=50)),
                ('stat1_label', models.CharField(default='Years of Service', max_length=100)),
                ('stat2_value', models.CharField(default='5000+', max_length=50)),
                ('stat2_label', models.CharField(default='Alumni Network', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
