# Generated by Django 6.0 on 2025-12-20 13:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g. Heart, Zap, Users, Shield)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='mission_text',
            field=ckeditor.fields.RichTextField(default='<ul><li>Provide a safe and stimulating learning environment.</li><li>Encourage critical thinking and creativity.</li><li>Instill strong moral values and social responsibility.</li></ul>', help_text='Use a bulleted list for mission items.'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_page/'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='principal_name',
            field=models.CharField(default='Dr. Vijay Kumar', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='principal_quote',
            field=models.TextField(default="Education is the most powerful weapon which you can use to change the world. At Nethaji, we don't just teach; we inspire."),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='principal_title',
            field=models.CharField(default='Principal', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='vision_text',
            field=models.TextField(default='To be a global leader in education, fostering a culture of innovation, integrity, and inclusivity, where every student is empowered to realize their full potential.'),
        ),
    ]
