# Generated by Django 6.0 on 2025-12-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_corevalue_aboutpagecontent_mission_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Journey', max_length=200)),
                ('hero_subtitle', models.CharField(default='EST. 2001', max_length=100)),
                ('hero_description', models.TextField(default='From a small classroom to a leading institution, explore the milestones that define our legacy.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='history/')),
                ('cta_title', models.CharField(default='Be Part of Our Future', max_length=200)),
                ('cta_description', models.TextField(default='The story of Nethaji Vidyalayam is still being written. Join us and help shape the next chapter of excellence.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'History Page Content',
                'verbose_name_plural': 'History Page Content',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='milestones/')),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g. Building, TrendingUp, Calendar, Award)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['order', 'year'],
            },
        ),
    ]
