# Generated by Django 6.0 on 2025-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historypagecontent_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='milestones/'),
        ),
    ]
