# Generated by Django 5.1.5 on 2026-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_milestone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Image to show while video is loading', null=True, upload_to='hero_videos/thumbnails/'),
        ),
    ]
