# Generated by Django 5.1.5 on 2026-01-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_herovideo_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(default='Vijaya Dhasami 2025', max_length=100)),
                ('title', models.CharField(default='ADMISSIONS OPEN NOW', max_length=200)),
                ('sub_title', models.CharField(default='PreKG TO 5th Grade', max_length=200)),
                ('discount_text', models.CharField(default='50% DISCOUNT', max_length=100)),
                ('discount_sub_text', models.CharField(default='On Tuition Fee', max_length=100)),
                ('extra_benefit', models.CharField(default='No Donation', max_length=100)),
                ('event_date', models.CharField(default='2 OCT, 10 AM', max_length=100)),
                ('event_name', models.CharField(default='AKSHARABHYASAM', max_length=100)),
                ('location', models.CharField(default='Medavakkam, Chennai', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poster',
                'verbose_name_plural': 'Posters',
            },
        ),
    ]
