# Generated by Django 5.1.5 on 2026-01-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='event_sub_name',
            field=models.CharField(default='Event Celebration', max_length=100),
        ),
        migrations.AddField(
            model_name='poster',
            name='event_tag',
            field=models.CharField(default='Special Initiation', max_length=100),
        ),
        migrations.AddField(
            model_name='poster',
            name='header_sub_title',
            field=models.CharField(default='Est. 2001 | 25 Years of Excellence', max_length=200),
        ),
    ]
