# Generated by Django 5.1.5 on 2026-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_feepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default QR', max_length=100)),
                ('qr_image', models.ImageField(upload_to='payment_qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment QR',
                'verbose_name_plural': 'Payment QRs',
            },
        ),
    ]
