# Generated by Django 5.1.5 on 2026-01-24 07:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_paymentqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='mission_text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Provide a safe and stimulating learning environment.</li><li>Encourage critical thinking and creativity.</li><li>Instill strong moral values and social responsibility.</li></ul>', help_text='Use a bulleted list for mission items.', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='story_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Our Story'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Provide the about section description.', verbose_name='Description'),
        ),
    ]
